---
core:
  num_workers: 100
inventory:
  plugin: nornir.plugins.inventory.netbox.NBInventory
  options:
    nb_url: 'http://0.0.0.0:32768'
    nb_token: '0123456789abcdefg0123456789'
    ssl_verify: False
